#! /usr/bin/env bash

[ -n "$(which pbcopy)" ] || echo 'could not find pbcopy'; exit 1

function usage()
{
  echo "usage ${0##*/} <file_path>"
  return 0
}

if [ $# -eq 1 ]
then
  if [ -f "$1" ]
  then
    if [ -r "$1" ]
    then
      pbcopy < "$1"
    else
      echo "unable to read \"${1}\""
      exit 1
    fi
  else
    echo "\"${1}\" is not a file"
    exit 1
  fi
else
  usage
  exit 1
fi

