#! /usr/bin/env bash

function usage()
{
  echo "usage ${0##*/} <file_path>"
  return 0
}

if [ $# -eq 1 ]
then
  if [ -f "$1" ]
  then
    if [ -w "$1" ]
    then
      echo "$(pbpaste)" >> "$1"
    else
      echo "unable to write \"${1}\""
      exit 1
    fi
  else
    echo "\"${1}\" is not a file"
    exit 1
  fi
else
  usage
  exit 1
fi

